# Generated by Django 6.0 on 2026-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.png', upload_to='emp_images'),
        ),
    ]
